/* Zone definitions: times tables, tile maps, terrain, characters, items.

   Map legend (every row is 14 tiles, 10 rows per zone):
     #  blocked terrain (trees, rocks, coral...)   ~  water / hazard (blocked)
     ,  walkable ground with decoration            .  walkable ground
     S  Whisker's start    G  the zone gate    1-4  characters
*/

const ZONES = [
  {
    id: 'meadow',
    name: 'Sunny Meadow',
    emoji: '🌻',
    tables: [1, 2],
    color: '#f9a826',
    ground: '#b5dd8a', groundAlt: '#aad47e', water: '#7ec8e3',
    blockEmoji: '🌳', decorEmoji: '🌼',
    item: { emoji: '🌻', name: 'sunflower', plural: 'sunflowers' },
    map: [
      '##############',
      '#.S..,...##..#',
      '#....1.......#',
      '#,##......,..#',
      '#....~~~..2..#',
      '#.,..~~~.....#',
      '#3......##..,#',
      '#..,.....4...#',
      '#......,....G#',
      '##############',
    ],
    characters: [
      { emoji: '🐰', name: 'Pip the Bunny', line: 'I hop in twos all day! Solve my puzzles for a sunflower!' },
      { emoji: '🐞', name: 'Dot the Ladybug', line: 'Help me count my spots and the sunflower is yours!' },
      { emoji: '🦋', name: 'Flutter the Butterfly', line: 'I flutter by with a puzzle just for you!' },
      { emoji: '🐝', name: 'Buzz the Bee', line: 'Buzz buzz! Answer my riddles, sweet as honey!' },
    ],
  },
  {
    id: 'woods',
    name: 'Whisker Woods',
    emoji: '🌲',
    tables: [3, 4],
    color: '#5b9c4a',
    ground: '#8fbf6e', groundAlt: '#85b765', water: '#6db5d8',
    blockEmoji: '🌲', decorEmoji: '🍂',
    item: { emoji: '🌰', name: 'acorn', plural: 'acorns' },
    map: [
      '##############',
      '#S...#..2..#.#',
      '#.,#...##....#',
      '#...1....#.,.#',
      '##..#..,...#.#',
      '#..,...#.3...#',
      '#.#...#....#.#',
      '#...#..,#....#',
      '#.4....#....G#',
      '##############',
    ],
    characters: [
      { emoji: '🦉', name: 'Professor Hoot', line: 'Hoo-hoo! A wise cat learns the threes and fours!' },
      { emoji: '🐿️', name: 'Nutmeg the Squirrel', line: 'I trade acorns for answers — best deal in the woods!' },
      { emoji: '🦊', name: 'Fern the Fox', line: 'A clever fox loves a clever cat. Try this!' },
      { emoji: '🦔', name: 'Pokey the Hedgehog', line: 'Don’t get stuck — my puzzles are sharp!' },
    ],
  },
  {
    id: 'beach',
    name: 'Berry Beach',
    emoji: '🏖️',
    tables: [5, 6],
    color: '#2aa5a0',
    ground: '#f2dba8', groundAlt: '#edd49b', water: '#62b6d9',
    blockEmoji: '🪨', decorEmoji: '🐚',
    item: { emoji: '🐚', name: 'seashell', plural: 'seashells' },
    map: [
      '##############',
      '#.S....,..1..#',
      '#...,........#',
      '#~~~....##...#',
      '#~~2..,....,.#',
      '#~~~~...3....#',
      '#~~~~~.....#.#',
      '#...~~~..,...#',
      '#.4........G.#',
      '##############',
    ],
    characters: [
      { emoji: '🦀', name: 'Snappy the Crab', line: 'Snip snap! Count by fives or I’ll pinch your toes!' },
      { emoji: '🐢', name: 'Shelly the Turtle', line: 'Slow and steady solves the puzzle every time.' },
      { emoji: '🐬', name: 'Splash the Dolphin', line: 'Eee-ee! Splash into this one!' },
      { emoji: '🦜', name: 'Coco the Parrot', line: 'Squawk! Coco wants an ANSWER! Squawk!' },
    ],
  },
  {
    id: 'hollow',
    name: 'Mushroom Hollow',
    emoji: '🍄',
    tables: [7, 8],
    color: '#c0564f',
    ground: '#a98fc0', groundAlt: '#a187b8', water: '#5f87b8',
    blockEmoji: '🍄', decorEmoji: '✨',
    item: { emoji: '🍄', name: 'glow-shroom', plural: 'glow-shrooms' },
    map: [
      '##############',
      '#..#..S...#..#',
      '#.1...,..#...#',
      '#...##.......#',
      '#,..#..2..,#.#',
      '#......##....#',
      '#.#.3....#...#',
      '#....,#...4..#',
      '#.#.......G..#',
      '##############',
    ],
    characters: [
      { emoji: '🐸', name: 'Croaky the Toad', line: 'Ribbit! The sevens and eights are tricky — but so are you!' },
      { emoji: '🐌', name: 'Doodle the Snail', line: 'Take your time... I always do...' },
      { emoji: '🪲', name: 'Glow the Beetle', line: 'My light shines for smart explorers!' },
      { emoji: '🐛', name: 'Inch the Caterpillar', line: 'Inch by inch, you’ll get it!' },
    ],
  },
  {
    id: 'cave',
    name: 'Crystal Cave',
    emoji: '💎',
    tables: [9, 10],
    color: '#6f5fb5',
    ground: '#9aa3c2', groundAlt: '#929bbb', water: '#4f6fa8',
    blockEmoji: '🪨', decorEmoji: '🔮',
    item: { emoji: '💎', name: 'crystal', plural: 'crystals' },
    map: [
      '##############',
      '#S..#...,..#.#',
      '#..#...1.....#',
      '#,....##..,#.#',
      '#..2.....#...#',
      '####.,..3....#',
      '#....#.....#,#',
      '#.,...#..4...#',
      '#..#......G..#',
      '##############',
    ],
    characters: [
      { emoji: '🦇', name: 'Echo the Bat', line: 'Echo... echo... answer my riddle... riddle...' },
      { emoji: '🐭', name: 'Pebble the Mouse', line: 'Squeak! I hid a crystal just for you!' },
      { emoji: '🕷️', name: 'Webster the Spider', line: 'I spin webs AND number puzzles!' },
      { emoji: '🐉', name: 'Spark the Dragon', line: 'A dragon-sized challenge for a brave little cat!' },
    ],
  },
  {
    id: 'summit',
    name: 'Star Summit',
    emoji: '⭐',
    tables: [11, 12],
    color: '#e2731c',
    ground: '#e8eef5', groundAlt: '#dfe7f0', water: '#b8d4ea',
    blockEmoji: '🗻', decorEmoji: '❄️',
    item: { emoji: '⭐', name: 'star', plural: 'stars' },
    map: [
      '##############',
      '#..S...~~..1.#',
      '#.,....~~....#',
      '#...2......,.#',
      '#~~....##....#',
      '#~~~..3...~~.#',
      '#......,..~~.#',
      '#.#..4.......#',
      '#.....,....G.#',
      '##############',
    ],
    characters: [
      { emoji: '🦅', name: 'Gale the Eagle', line: 'Only the sharpest minds reach the summit!' },
      { emoji: '🐐', name: 'Billy the Goat', line: 'Maaa! I climbed all the way up for this puzzle!' },
      { emoji: '☁️', name: 'Nimbus the Cloud', line: 'Whoosh... the elevens and twelves float my way...' },
      { emoji: '🌟', name: 'Twinkle the Star', line: 'Shine bright! This is the final challenge!' },
    ],
  },
];

/* Whisker's School: one lesson per table. `trick` lines are shown one by one.
   `widget: 'fingers'` adds the interactive ×9 finger-trick. */
const LESSONS = {
  1:  { trick: ['×1 is the MIRROR table — any number times 1 is just itself!',
                '1 × 8 = 8. 1 × 12 = 12. The number looks in the mirror and sees... itself! 🪞'],
        example: [1, 8] },
  2:  { trick: ['×2 means DOUBLES — just add the number to itself!',
                '2 × 7 is 7 + 7 = 14. If you can add, you can do the whole twos table! 👯'],
        example: [2, 7] },
  3:  { trick: ['×3 is DOUBLE PLUS ONE MORE!',
                '3 × 6: double 6 is 12... then add one more 6 to get 18!',
                'Try skip-counting out loud with a beat: 3, 6, 9, 12 — it’s a song! 🎵'],
        example: [3, 6] },
  4:  { trick: ['×4 is the DOUBLE-DOUBLE! Double the number... then double it again!',
                '4 × 6: double 6 is 12, double 12 is 24. Two quick doubles! 🍔🍔'],
        example: [4, 6] },
  5:  { trick: ['Every ×5 answer ends in 5 or 0 — no exceptions!',
                'Count by 5s like minutes on a clock: 5, 10, 15, 20...',
                'Big number? ×5 is HALF of ×10. 5 × 8: 10 × 8 = 80, half is 40! ⏰'],
        example: [5, 8] },
  6:  { trick: ['×6 is ×5 plus ONE MORE GROUP. 6 × 7: five 7s are 35, plus 7 is 42!',
                'Secret pattern: 6 × an EVEN number ends in that same number! 6×2=12, 6×4=24, 6×8=48 — the answer ends with the number you multiplied! 🕵️'],
        example: [6, 7] },
  7:  { trick: ['Sneaky sevens! Use the TURN-AROUND trick: 7 × 3 is the same as 3 × 7 — pick the table you know best!',
                'And remember the famous one: 5, 6, 7, 8 → “56 = 7 × 8”! 🎲'],
        example: [7, 8] },
  8:  { trick: ['×8 is the DOUBLE-DOUBLE-DOUBLE! Three doubles in a row!',
                '8 × 5: 5 → 10 → 20 → 40. Whoosh!',
                'And the silly rhyme: “I ate and ate ’til I was sick on the floor — 8 times 8 is 64!” 🤢'],
        example: [8, 8] },
  9:  { trick: ['Nines have FINGER MAGIC — your hands know the whole table! Try it below! 🖐️🖐️',
                'Double-check trick: the digits of every ×9 answer add up to 9! 27 → 2+7=9, 54 → 5+4=9!'],
        example: [9, 7], widget: 'fingers' },
  10: { trick: ['The easiest table in the world: just hang a ZERO on the end!',
                '10 × 7 = 70. 10 × 12 = 120. Done before you blink! 😎'],
        example: [10, 7] },
  11: { trick: ['×11 makes TWIN numbers! 11 × 4 = 44. 11 × 7 = 77. Twins up through 9!',
                'For the big ones, split it: 11 × 12 = (10 × 12) + 12 = 132. 👯‍♀️'],
        example: [11, 4] },
  12: { trick: ['×12 = ×10 plus ×2 — split it into two easy jobs!',
                '12 × 6: ten 6s are 60, two 6s are 12... 60 + 12 = 72! ✂️'],
        example: [12, 6] },
};

const TEACHER_PRAISE = [
  'You’re getting so strong at this!', 'Look at that brain go! 🧠',
  'Whisker is doing a happy dance!', 'That was QUICK! Amazing!',
  'You’ll be teaching ME soon!', 'Gold star thinking! ⭐',
];

const PRAISE = [
  'Purr-fect!', 'Paw-some job!', 'Meow-nificent!', 'You’re a star!',
  'Whisker is so proud!', 'Cat-tastic!', 'Super smart!', 'Brilliant!',
];

const ENCOURAGE = [
  'So close! Try once more!', 'Almost! You can do it!',
  'Hmm, not quite — one more try!', 'Whisker believes in you!',
];
